name: CI

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Poetry
        uses: snok/install-poetry@v1
#      - name: Cache Poetry virtualenv
#        uses: actions/cache@v1
#        id: cache
#        with:
#          path: ~/.virtualenvs
#          key: poetry-${{ hashFiles('**/poetry.lock') }}
#          restore-keys: |
#            poetry-${{ hashFiles('**/poetry.lock') }}

#      - name: Set Poetry config
#        run: |
#          poetry config settings.virtualenvs.in-project false
#          poetry config settings.virtualenvs.path ~/.virtualenvs

      - name: Install Dependencies
        run: poetry install
#        if: steps.cache.outputs.cache-hit != 'true'

      - name: Code Quality
        run: poetry run black . --check

      - name: Test with pytest
        env:
          CODECOV_TOKEN: '1af5f6c7-23ad-4b3f-9a96-9e5b816707bc'
        #          DJANGO_SETTINGS_MODULE: project.settings
        #          SECRETS_FILE: .confidential/ci.json
        run: poetry run pytest --cov . --cov-report=xml

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          files: ./coverage.xml
          token: '1af5f6c7-23ad-4b3f-9a96-9e5b816707bc'
#          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos

